### ISSUE TITLE
[#1] Implementacion Red de Petri

### ISSUE THREAD

**Issue by franco-viotti** [brian1062/tp_final_programacion_concurrente#1]
Implementar la red de Petri de la Figura 1 haciendo uso de una herramienta, ej: PIPE. Verificar todas sus propiedades.

**Comment by brian1062** [comment]
[Diagrama echo en petrinator](https://drive.google.com/file/d/1wR82mD9PwCp1jTfzOi0B-dW9f2ydWnG2/view?usp=sharing)
![image](https://github.com/user-attachments/assets/81be453d-2475-4ca2-b81f-4577f07791a4)
